version: "3.2"

services:
  interlock-helloweb:
    image: grahamh/hello-docker-web:3.0
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: helloweb.apps.example.org
        com.docker.lb.network: helloweb-net
        com.docker.lb.port: 8080
    networks:
      - helloweb-net

networks:
  helloweb-net:
    driver: overlay

